### ISSUE TITLE
uni_router/universal_swap_from_token.py

### ISSUE THREAD

**Issue by FirstonTheBlock** [0xMaka/w3py#6]
Hi,

Is this easily changed to interact with V2 Router?

Thanks.

**Comment by 0xMaka** [comment]
As in to use the Universal Router to perform a V2, rather than V3 swap?

If so then yes it will be almost identical, other than the swap encoding, noticeably would use a different path structure, just a `[token_in,token_out]` array rather than `encode_packed(token_in,fee,_token_out)`.

Encode the following for the swap:
```
# V2_SWAP_EXACT_IN
address    : The recipient of the output of the trade
uint256    : The amount of input tokens for the trade
uint256    : The minimum amount of output tokens the user wants
address[]  : The UniswapV2 token path to trade along
bool         : A flag for whether the input tokens should come from the msg.sender (through Permit2) or whether the funds are already in the UniversalRouter
```

As well as change the command byte from `0x00` to `0x08`.
ref: https://docs.uniswap.org/contracts/universal-router/technical-reference#v2_swap_exact_in

If meaning something else, and you can clarify will be happy to add a direct example.

**Comment by FirstonTheBlock** [comment]
Yes that's it. If you could add a V2 version for buy and sell that would be amazing. Many thanks 🙏

**Comment by FirstonTheBlock** [comment]
Oops I closed this by mistake. Teach me to reply on my phone!

**Comment by 0xMaka** [comment]
Have added an example variant that swaps on a v2 pool:
- https://github.com/0xMaka/w3py/blob/main/uni_router/universal_v2_swap.py

Example was tested on polygon, and uses the same abi as the original `universal_swap_from_token.py`

Will close this issue, please reopen if have additional questions. Much love 🙏🏽

**Comment by FirstonTheBlock** [comment]
Many thanks, I appreciate it. :)
